# This docker-compose file is used to build and manage the container built from the Docker image 
# that encapsulates the Laika BOSS: Object Scanning System by Lockheed Martin Corporation 
# from https://github.com/lmco/laikaboss 
#
# To build the container after installing Docker and Docker Compose using a standalone instance, 
# use a command like the following, replacing “~/laikaboss-workdir" with the path to the location 
# of your Laika BOSS working directory:
#
# sudo docker-compose up -d
#
# To run this image using a networked instance, uncomment the lines that specify the ports and 
# run the command above.
#
# To remove the container, image, and volume, run the following command:
#
# sudo docker-compose down --rmi all
#
# Before running Laika BOSS, create the ~/laikaboss-workdir and make it world-accessible
# (“chmod a+xwr"). If you would like to build the container from the provided Dockerfile, 
# uncomment the build and context lines.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Retrieve current version of Yara via wget, verify known good hash and install Yara
# Retrieve pyexiftool, verify known good hash and install pyexiftool
# Retrieve current version of pefile via wget, verify known good hash and install pefile
# Retrieve current version of jq via wget, verify known good hash and move to /usr/local/bin
# Install additional dependencies
# Add nonroot user, clone repo and setup environment
# Clone Laika BOSS from GitHub as nonroot user
# Run setup script to install Laika BOSS framework, client library, modules and associated scripts (laika.py, laikad.py, cloudscan.py)
# Clean up and run ldconfig
# Build container

version: '2'

services:
  laikaboss:
#    build:
#      context: .
    image: wzod/laikaboss
    labels:
      - 'laikaboss'
#    ports:
#      - '5558:5558'
    restart: always
    volumes:
      - '~/laikaboss-workdir:/home/nonroot/workdir'
    tty: true
